import { IMAGES } from '../assets';

export const hightlightData = [
	{
		id: 1,
		src: IMAGES.high1,
		text: 'VISION 2030 - EMERGENCE OF THE KINGDOM AS A GLOBAL FINANCIAL LEADER',
	},
	{
		id: 2,
		src: IMAGES.high2,
		text: 'DIGITAL TRANSFORMATION - THE FOUNDATIONAL PLATFORM FOR ACHIEVING BUSINESS AGILITY',
	},
	{
		id: 3,
		src: IMAGES.high3,
		text: 'PAYMENTS TODAY & TOMORROW - THE FUTURE OF DIGITAL PAYMENTS',
	},
	{
		id: 4,
		src: IMAGES.high4,
		text: 'PROVIDING A NEXT-GEN SEAMLESS BANKING CUSTOMER EXPERIENCE',
	},
	{
		id: 5,
		src: IMAGES.high5,
		text: 'DATA & ANALYTICS PROVIDING A 360° OVERVIEW TO BANKS & CUSTOMERS',
	},
	{
		id: 6,
		src: IMAGES.high6,
		text: 'INCLUSIVE BANKING THROUGH OPEN BANKING - BRINGING LEGACY BANKS AND FINTECHS TOGETHER',
	},
	{
		id: 7,
		src: IMAGES.high7,
		text: 'THE CLOUD IMPERATIVE - A KEY ENABLER FOR BANKS TO ACHIEVE BUSINESS AGILITY THROUGH CLOUD-POWERED DIGITAL TRANSFORMATION',
	},
	{
		id: 8,
		src: IMAGES.high8,
		text: 'THE FUTURE OF NBFIs - REVOLUTIONIZING THE MONEY MARKET IN KSA',
	},
	{
		id: 9,
		src: IMAGES.high9,
		text: 'DIGITAL ONLY BANKS - THE RISE OF INVISIBLE BANKS FOR GEN-Z CUSTOMERS',
	},
	{
		id: 10,
		src: IMAGES.high10,
		text: 'EXPERIENTIAL BANKING IN METAVERSE - THE THIRD WORLD BANKING',
	},
];
